name: Java CI with Gradle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: build
        run: ./gradlew build

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: PCTools
          path: build/libs/*.jar
